views:
  - path: default_view
    title: Home
    cards:
      - type: custom:donut
        entity: sensor.example_level
      - type: custom:tunk
        entity: sensor.example_level
      - type: custom:cistern
        entity: sensor.example_level
      - type: custom:tile
        entity: sensor.example_level
