views:
  - path: default_view
    title: G-Septik
    badges:
      - type: entity
        entity: weather.demo_weather_north
        color: red
    cards:
      - type: custom:septic-tank-card
        entities:
          level: sensor.uroven_zhidkosti_septika
          temp: sensor.temperatura_septika
          pressure: sensor.davlenie_septika
          x_level: sensor.kriticheskii_uroven_septika
          exceeds_x_level: sensor.prevyshen_kriticheskii_uroven_septika
          sdt: sensor.uroven_signala_septika
          error_name: sensor.oshibka_septika
        tank:
          header:
            show: true
            label: My Septic Tank
          level:
            show: true
          scale:
            position: left
      - type: custom:septic-tank-card
        entities:
          level: sensor.uroven_zhidkosti_septika
          temp: sensor.temperatura_septika
          pressure: sensor.davlenie_septika
          x_level: sensor.kriticheskii_uroven_septika
          exceeds_x_level: sensor.prevyshen_kriticheskii_uroven_septika
          sdt: sensor.uroven_signala_septika
          error_name: sensor.oshibka_septika
        level:
          show: true
        temp:
          show: true
        pressure:
          show: true
        x_level:
          show: true
        exceeds_x_level:
          show: true
        sdt:
          show: true
        error_name:
          show: true
      - type: entities
        title: G-Septik
        state_color: false
        show_header_toggle: false
        entities:
          - entity: sensor.uroven_zhidkosti_septika
            icon: mdi:water-percent
          - entity: sensor.temperatura_septika
            icon: mdi:thermometer
          - entity: sensor.davlenie_septika
            icon: mdi:gauge
          - entity: sensor.kriticheskii_uroven_septika
            icon: mdi:water-minus
          - entity: sensor.prevyshen_kriticheskii_uroven_septika
            icon: mdi:water-alert
          - entity: sensor.uroven_signala_septika
            icon: mdi:signal
          - entity: sensor.oshibka_septika
            icon: mdi:alert-decagram-outline
