views:
  - path: default_view
    title: Screenshot
    badges:
      - type: entity
        entity: weather.demo_weather_north
        color: red
    cards:
      - type: custom:septic-tile-card
        entities:
          level: septic_tank_liquid_level
          temp: septic_tank_temperature
          pressure: septic_tank_pressure
          x_level: septic_tank_critical_level
          exceeds_x_level: septic_tank_exceeds_critical_level
          error_name: septic_tank_error
      - type: custom:septic-tank-card
        entities:
          level: septic_tank_liquid_level
          temp: septic_tank_temperature
          pressure: septic_tank_pressure
          x_level: septic_tank_critical_level
          exceeds_x_level: septic_tank_exceeds_critical_level
          error_name: septic_tank_error
      - type: custom:septic-tank-card
        entities:
          level: septic_tank_liquid_level
          temp: septic_tank_temperature
          pressure: septic_tank_pressure
          x_level: septic_tank_critical_level
          exceeds_x_level: septic_tank_exceeds_critical_level
          error_name: septic_tank_error
        header:
          show: true
        level:
          show: true
        temp:
          show: true
        pressure:
          show: true
        x_level:
          show: true
        exceeds_x_level:
          show: true
        error_name:
          show: true
